config/urls.py
from django.contrib import admin
from django.urls import path

# config/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
#  hello/urls.py

from django.shortcuts import render
from . import views
from django.urls import path

app_name = "website"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('home', views.home_page_view, name='home'),
    path('search', views.search_page_view, name='search'),
    path('explore', views.explore_page_view, name='explore'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render

# Create your views here.

#  hello/views.py

from django.shortcuts import render


def home_page_view(request):
    return render(request, 'website/home.html')


def search_page_view(request):
    return render(request, 'website/search.html')


def explore_page_view(request):
    return render(request, 'website/explore.html')

website/templates/website/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>lab6 </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="shortcut icon" type="image/png" href="{% static 'website/images/favicon.ico' %}"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
</head>

<body>

<header class="jumbotron text-center">
    <h1>Titulo web site</h1>
    <p>Lorem impsum dolor</p>
    <nav>
        <a href="{% url 'website:home' %}" class="btn btn-info">Home</a>
        <a href="{% url 'website:search' %}" class="btn btn-info">Search</a>
        <a href="{% url 'website:explore' %}" class="btn btn-info">Explore</a>
    </nav>
</header>

<article class="container">
    <main class="col-sm-6">
        {% block main %}
        {% endblock main %}
    </main>
    <aside class="col-sm-6">
        {% load static %}
        <img src="{% static 'website/images/200pxwidthimg.jfif' %}">
    </aside>
</article>

<footer>Bottom text funny ahaha</footer>

</body>

</html>

website/templates/website/explore.html
<!-- explore.html -->

{% extends 'website/base.html' %}

{% block main %}
    <h3>explore</h3>
    <p>texto 3 </p>
{% endblock %}

website/templates/website/home.html
<!-- home.html -->

{% extends 'website/base.html' %}

{% block main %}
    <h3>home</h3>
    <p>texto 1 </p>
{% endblock %}

website/templates/website/search.html
<!-- search.html -->

{% extends 'website/base.html' %}

{% block main %}
    <h3>search</h3>
    <p>texto 2 </p>
{% endblock %}